export const HEURISTICS = [
  { id: 1, title: { en: "Request adequacy", fr: "Adéquation de la requête" }, summary: { en: "Did the agent grasp the intent and adopt the expected response structure?", fr: "L'agent a-t-il saisi l'intention et adopté la structure de réponse attendue ?" }, bullets: { en: ["Does the answer follow the expected format?", "Does the agent avoid off-topic answers?", "Does it fully cover the request?", "Is key info immediately readable?"], fr: ["La réponse respecte-t-elle le format attendu ?", "L'agent évite-t-il les réponses hors sujet ?", "La réponse couvre-t-elle l'intégralité de la demande ?", "La structure facilite-t-elle la lecture immédiate ?"] } },
  { id: 2, title: { en: 'Reasoning transparency ("Why")', fr: "Transparence du raisonnement (« Pourquoi »)" }, summary: { en: "The AI must show its thinking steps. Users should not have to take its word for it.", fr: "L'IA doit montrer ses étapes de pensée. L'utilisateur ne doit pas avoir à croire l'agent sur parole." }, bullets: { en: ["Does it explain why it proposes this action?", "Does it surface its sources or assumptions?", "Can the user trace a recommendation to its origin?"], fr: ["L'agent explique-t-il pourquoi il propose cette action ?", "Rend-il visibles ses sources ou hypothèses ?", "L'utilisateur peut-il retracer l'origine d'une recommandation ?"] } },
  { id: 3, title: { en: 'Contextual relevance ("Where")', fr: "Pertinence contextuelle (« Où »)" }, summary: { en: "The AI must know where we are in the workflow and who it's talking to.", fr: "L'IA doit savoir où l'on est dans le workflow et avec qui elle parle." }, bullets: { en: ["Are suggestions adapted to the workflow stage?", "Does it understand the user's role?", "Does it adapt vocabulary to the profile?", "Does it avoid unavailable actions?"], fr: ["Les suggestions sont-elles adaptées à l'étape du workflow ?", "L'agent comprend-il le rôle de l'utilisateur ?", "Adapte-t-il son vocabulaire au profil détecté ?", "Évite-t-il les actions non disponibles ?"] } },
  { id: 4, title: { en: "Human controllability", fr: "Contrôlabilité humaine" }, summary: { en: "The human must be able to modify, refine, undo at any time. The agent assists, it does not decide.", fr: "L'humain doit pouvoir modifier, raffiner, annuler à tout moment. L'agent assiste, ne décide pas." }, bullets: { en: ["Can the user interrupt or hand-edit a suggestion?", "Are these actions easy mid-interaction?", "Is undo reversible with no side-effects?"], fr: ["Possibilité d'interrompre ou modifier une suggestion manuellement ?", "Ces actions sont-elles faciles en cours d'interaction ?", "L'annulation est-elle réversible et sans effet de bord ?"] } },
  { id: 5, title: { en: "Cognitive load reduction", fr: "Réduction de la charge cognitive" }, summary: { en: "The AI must synthesize, not add noise. Too much unsolicited detail is as bad as too little.", fr: "L'IA doit synthétiser, pas ajouter du bruit. Trop de détails non sollicités est aussi mauvais que trop peu." }, bullets: { en: ["Is interacting simpler than classic menus?", "Does it simplify the task?", "Are answers appropriately sized?", "Does it offer summaries for complex answers?"], fr: ["L'interaction est-elle plus simple que les menus classiques ?", "Simplifie-t-elle la tâche ?", "Les réponses sont-elles bien calibrées ?", "Propose-t-elle des résumés pour les réponses complexes ?"] } },
  { id: 6, title: { en: 'Reliability & anticipation ("Safeguards")', fr: "Fiabilité & anticipation (« Garde-fous »)" }, summary: { en: "The agent must own its uncertainty and block impossible or destructive actions.", fr: "L'agent doit avouer ses doutes et bloquer les actions impossibles ou destructrices." }, bullets: { en: ["Does it ask for clarification on ambiguity?", "Does it detect impossible parameters?", "Does it express confidence levels?", "Does it anticipate downstream consequences?"], fr: ["Demande-t-elle clarification en cas d'ambiguïté ?", "Détecte-t-elle les paramètres impossibles ?", "Exprime-t-elle un niveau de confiance ?", "Anticipe-t-elle les conséquences négatives en aval ?"] } },
  { id: 7, title: { en: 'Action segmentation ("How")', fr: "Segmentation des actions (« Comment »)" }, summary: { en: "Break a complex goal into reachable steps, like an expert guiding a peer step by step.", fr: "Décomposer un objectif complexe en étapes atteignables, comme un expert qui guide un collègue." }, bullets: { en: ["Can it break a complex request into sub-steps?", "Are steps coherently ordered?", "Does it indicate links between steps?"], fr: ["Sait-elle segmenter une demande complexe en sous-étapes ?", "Les étapes sont-elles ordonnées de manière cohérente ?", "Indique-t-elle les liens entre les étapes ?"] } },
  { id: 8, title: { en: "Bridge to interface and 3D model", fr: "Relation avec l'interface et le modèle 3D" }, summary: { en: "Bridges between dialogue and direct manipulation: see what's selected, show answers graphically.", fr: "Ponts entre dialogue et manipulation directe : voir ce qui est sélectionné, montrer graphiquement ses réponses." }, bullets: { en: ["Can the user point to a 3D object as the subject?", "Can the AI highlight relevant zones?", "Does it keep dialogue ↔ 3D view in sync?", "Can it generate annotations on the model?"], fr: ["L'utilisateur peut-il désigner un objet 3D comme sujet ?", "L'IA met-elle en évidence les zones importantes ?", "Maintient-elle la synchronisation dialogue ↔ vue 3D ?", "Peut-elle générer des annotations sur le modèle ?"] } },
  { id: 9, title: { en: "Interoperability (access to project data)", fr: "Interopérabilité (accès aux données projet)" }, summary: { en: "The agent must extract and correlate data from CATIA, ENOVIA, material libraries, etc.", fr: "L'agent doit pouvoir extraire et corréler des données venant de CATIA, ENOVIA, librairies matériaux, etc." }, bullets: { en: ["Can it answer using data not in the current interface?", "Does it clearly state which data source it consulted?"], fr: ["Peut-il répondre en utilisant des données absentes de l'interface actuelle ?", "Indique-t-il clairement quelle source de données il a consultée ?"] } },
  { id: 10, title: { en: 'Consistency over time ("Memory")', fr: "Cohérence dans le temps (« Mémoire »)" }, summary: { en: "The AI must remember the engineer's style and decisions taken earlier in the session.", fr: "L'IA doit se souvenir du style de l'ingénieur et des décisions prises plus tôt dans la session." }, bullets: { en: ["Do responses stay consistent across the session?", "Does it remember earlier information?", "Does it flag contradictions with earlier decisions?", "Does it distinguish session vs project memory?"], fr: ["Les réponses restent-elles constantes dans la session ?", "L'agent se rappelle-t-il des informations données plus tôt ?", "Détecte-t-il une contradiction avec une décision prise plus tôt ?", "Distingue-t-il mémoire de session et mémoire projet ?"] } },
]

export function scoreMeta(score) {
  if (score === null || score === undefined) return { color: "var(--neutral)", bg: "rgba(148,163,184,0.15)", border: "var(--neutral)" }
  if (score === 5) return { color: "var(--success)", bg: "rgba(52,211,153,0.15)", border: "var(--success)" }
  if (score >= 3) return { color: "var(--warning)", bg: "rgba(251,191,36,0.15)", border: "var(--warning)" }
  return { color: "var(--danger)", bg: "rgba(248,113,113,0.15)", border: "var(--danger)" }
}